import { Template, TemplateType } from "./types";

export const syncTemplates: Template[] = [
  {
    id: "100",
    type: TemplateType.GuideTextBox,
    title: "1분 자기소개 시간 ⏱️",
    x: 200,
    y: 30,
    width: 800,
    height: 25,
    font: 18,
    fontWeight: "600",
    fill: "none",
  },
  {
    id: "101",
    type: TemplateType.NoteBox,
    title:
      "정말 무슨 말이라도 좋아요! 팀원들이 서로를 잘 알고 편안한 감정을 가질 수록 팀 전체의 문제 해결 능력이 향상된다는 연구 결과가 있어요😃",
    x: 200,
    y: 85,
    height: 180,
    fill: "#E9F5FF",
  },
  {
    id: "102",
    type: TemplateType.GuideTextBox,
    title: "제 강점과 약점은요, 이렇게 생각해요!",
    x: 200,
    y: 270,
    width: 800,
    height: 25,
    font: 18,
    fontWeight: "600",
    fill: "none",
  },
  {
    id: "103",
    type: TemplateType.NoteBox,
    title:
      "사람은 모든 면에서 완벽할 수 없어요. 부끄러워하지 않아도 괜찮아요 ! 서로의 강점과 약점을 공유하는 시간을 가져봐요😉",
    x: 200,
    y: 320,
    height: 180,
    fill: "#E9F5FF",
  },
  {
    id: "104",
    type: TemplateType.GuideTextBox,
    title: "이것만은 부탁해요!",
    x: 200,
    y: 500,
    width: 800,
    height: 25,
    font: 18,
    fontWeight: "600",
    fill: "none",
  },
  {
    id: "105",
    type: TemplateType.NoteBox,
    title:
      "프로젝트를 시작하기 앞서, 팀원들에게 이것만은 솔직하게 부탁하고 싶어요!",
    x: 200,
    y: 550,
    height: 180,
    fill: "#E9F5FF",
  },

  {
    id: "200",
    type: TemplateType.GuideTextBox,
    title: "프로젝트 내 개인목표",
    x: 200,
    y: 1030,
    width: 800,
    height: 25,
    font: 18,
    fontWeight: "600",
    fill: "none",
  },

  {
    id: "201",
    type: TemplateType.NoteBox,
    title:
      "프로젝트를 통해 얻어가고 싶은 목표를 적어주세요 ! \n우리는 각자 프로젝트에서 얻어가고자 하는 목표가 다를 수 있고, 이 점을 서로 존중하고 이해해줘야 해요😌",
    x: 200,
    y: 1090,
    width: 800,
    height: 200,
    fill: "#E9F5FF",
  },
  {
    id: "202",
    type: TemplateType.GuideTextBox,
    title: "프로젝트 내 팀목표",
    x: 200,
    y: 1310,
    width: 800,
    height: 25,
    font: 18,
    fontWeight: "600",
  },
  {
    id: "203",
    type: TemplateType.NoteBox,
    title:
      "각자 다른 목표를 가지고 있어도, 우리는 결국 합의된 하나의 목표를 바라봐야해요.\n모두의 개인 목표를 토대로 우리 팀의 목표는 이걸로 하면 어떨까? 하는 의견을 자유롭게 적어주세요 !",
    x: 200,
    y: 1370,
    width: 800,
    height: 200,
    fill: "#E9F5FF",
  },
  {
    id: "204",
    type: TemplateType.GuideTextBox,
    title: "한 문장으로 팀의 목표를 정의해주세요💪🏻",
    x: 200,
    y: 1580,
    width: 800,
    height: 50,
    font: 18,
    fontWeight: "600",
  },
  {
    id: "205",
    type: TemplateType.InputFormBox,
    title: "한 문장으로 팀의 목표를 정의해주세요💪🏻",
    x: 200,
    y: 1640,
    width: 800,
    height: 50,
    font: 18,
    fontWeight: "600",
    value: "",
  },
  {
    id: "300",
    type: TemplateType.ThirdStepProb,
    title: "+",
    x: 200,
    y: 2050,
    width: 200,
    height: 200,
    fill: "#F5F5F5",
    value: 0,
  },
  {
    id: "400",
    type: TemplateType.GuideTextBox,
    title:
      "페르소나란 문제 상황을 겪는 가상의 인물을 의미해요👤\n인물의 나이/성별/배경(직업, 학력 등)/특징/목표/동기/문제 상황 등 자유롭게 문제 고객을 설정해주세요!\n이후 작성한 페르소나를 공유하고 문제 상황에 대해 공감해봐요😌",
    x: 75,
    y: 3020,
    width: 800,
    height: 200,
    font: 14,
    fontWeight: "300",
  },
  {
    id: "401",
    type: TemplateType.PersonaBox,
    title: "PersonaBox",
    x: 100,
    y: 3150,
    width: 300,
    height: 250,
    value: [
      { title: "info", value: "" },
      {
        title: "personality",
        value: "",
      },
      {
        title: "detail",
        value: "",
      },
    ],
  },
  {
    id: "801",
    type: TemplateType.NoteBox,
    title: "👤 우리 서비스가 초점을 맞출 핵심 타겟(최종 사용자)은?",
    x: 100,
    y: 7075,
    width: 500,
    height: 200,
    fill: "#E9F5FF",
  },
  {
    id: "802",
    type: TemplateType.NoteBox,
    title: "🤔 우리 서비스가 해결하고자 하는 근본적 문제와 그 원인은?",
    x: 100,
    y: 7325,
    width: 500,
    height: 200,
    fill: "#E9F5FF",
  },
  {
    id: "803",
    type: TemplateType.NoteBox,
    title: "🤩 우리 서비스가 최종 사용자에게 제공하고자 하는 솔루션 및 가치는?",
    x: 100,
    y: 7575,
    width: 500,
    height: 200,
    fill: "#E9F5FF",
  },
  {
    id: "804",
    type: TemplateType.GuideTextBox,
    title: "핵심 타겟",
    x: 650,
    y: 7050,
    width: 400,
    height: 50,
    fontWeight: "600",
    font: 16,
    fill: "none",
  },
  {
    id: "805",
    type: TemplateType.InputFormBox,
    title: "핵심 타겟",
    x: 650,
    y: 7105,
    width: 400,
    height: 50,
    font: 16,
    fontWeight: "600",
    value: "",
  },
  {
    id: "806",
    type: TemplateType.GuideTextBox,
    title: "근본 문제",
    x: 650,
    y: 7175,
    width: 800,
    height: 50,
    font: 16,
    fontWeight: "600",
  },
  {
    id: "807",
    type: TemplateType.InputFormBox,
    title: "Pain Point",
    x: 650,
    y: 7230,
    width: 400,
    height: 50,
    font: 16,
    fontWeight: "600",
    value: "",
  },
  {
    id: "808",
    type: TemplateType.GuideTextBox,
    title: "근본 원인",
    x: 650,
    y: 7300,
    width: 800,
    height: 50,
    font: 16,
    fontWeight: "600",
  },
  {
    id: "809",
    type: TemplateType.InputFormBox,
    title: "근본 원인",
    x: 650,
    y: 7355,
    width: 400,
    height: 50,
    font: 16,
    fontWeight: "600",
    value: "",
  },
  {
    id: "810",
    type: TemplateType.GuideTextBox,
    title: "해결 방안",
    x: 650,
    y: 7425,
    width: 800,
    height: 50,
    font: 16,
    fontWeight: "600",
  },
  {
    id: "811",
    type: TemplateType.InputFormBox,
    title: "해결 방안",
    x: 650,
    y: 7480,
    width: 400,
    height: 50,
    font: 16,
    fontWeight: "600",
    value: "",
  },
  {
    id: "812",
    type: TemplateType.GuideTextBox,
    title: "핵심 가치",
    x: 650,
    y: 7550,
    width: 800,
    height: 50,
    font: 16,
    fontWeight: "600",
  },
  {
    id: "813",
    type: TemplateType.InputFormBox,
    title: "핵심 가치",
    x: 650,
    y: 7605,
    width: 400,
    height: 50,
    font: 16,
    fontWeight: "600",
    value: "",
  },
  {
    id: "1000",
    type: TemplateType.GuideTextBox,
    title:
      "유저 시나리오란, 사용자가 서비스를 사용하는 과정에서 자신의 목표를 위해 어떻게 행동하는 지 구체적으로 기술한 것을 말해요.\n이러한 시나리오는 사용자의 경험을 더욱 깊이 이해하고, 놓쳤던 설계 상의 결함을 미리 파악할 수 있어요.\nSync-D는 이 단계에서 작성된 유저 시나리오를 통해서 기능 개발을 위한 작은 단위의 사용자 요구 명세, 즉 유저스토리를 작성해드려요!",
    x: 75,
    y: 9020,
    width: 800,
    height: 300,
    font: 14,
    fontWeight: "400",
  },
  {
    id: "1001",
    type: TemplateType.GuideTextBox,
    title: "시나리오 1",
    x: 90,
    y: 9110,
    width: 400,
    height: 50,
    font: 18,
    fontWeight: "600",
  },
  {
    id: "1002",
    type: TemplateType.InputFormBox,
    title: "시나리오를 작성해주세요",
    x: 100,
    y: 9170,
    width: 500,
    height: 50,
    font: 18,
    fontWeight: "600",
    value: "",
  },
  {
    id: "1003",
    type: TemplateType.GuideTextBox,
    title: "시나리오 2",
    x: 100,
    y: 9240,
    width: 400,
    height: 50,
    font: 18,
    fontWeight: "600",
  },
  {
    id: "1004",
    type: TemplateType.InputFormBox,
    title: "시나리오를 작성해주세요",
    x: 100,
    y: 9300,
    width: 500,
    height: 50,
    font: 18,
    fontWeight: "600",
    value: "",
  },
  {
    id: "1005",
    type: TemplateType.GuideTextBox,
    title: "시나리오 3",
    x: 100,
    y: 9370,
    width: 400,
    height: 50,
    font: 18,
    fontWeight: "600",
  },
  {
    id: "1006",
    type: TemplateType.InputFormBox,
    title: "시나리오를 작성해주세요",
    x: 100,
    y: 9430,
    width: 500,
    height: 50,
    font: 18,
    fontWeight: "600",
    value: "",
  },
  {
    id: "1007",
    type: TemplateType.GuideTextBox,
    title: "시나리오 4",
    x: 100,
    y: 9500,
    width: 400,
    height: 50,
    font: 18,
    fontWeight: "600",
  },
  {
    id: "1008",
    type: TemplateType.InputFormBox,
    title: "시나리오를 작성해주세요",
    x: 100,
    y: 9560,
    width: 500,
    height: 50,
    font: 18,
    fontWeight: "600",
    value: "",
  },
  {
    id: "1009",
    type: TemplateType.GuideTextBox,
    title:
      "Sync-D가 여러분이 작성해주신 유저 시나리오 에픽과 유저 스토리를 만들어 드렸어요!\n유저스토리는 기능 개발을 위해 사용자의 요구를 간결하고 명확하게 이해하고, 효과적으로 기능 단위 개발을 할 수 있도록 도와줘요.\n 에픽은 유저스토리의 상위 개념으로, 여러 유저스토리로 나뉠 수 있는 큰 단위의 작업량을 가진 업무를 의미해요.\nSync-D가 제공한 에픽과 유저스토리를 확인하고, 서비스의 방향에 맞게 수정/보완해주세요!",
    x: 75,
    y: 10020,
    width: 800,
    height: 300,
    font: 14,
    fontWeight: "400",
  },
  {
    id: "1200",
    type: TemplateType.GuideTextBox,
    title:
      "우리 서비스의 페이지는 어떻게 나뉠 수 있을까요?\n또 페이지들 마다 어떤 기능들을 가지고 있을까요? \n좌측 상단 도움말을 눌러 예시 이미지를 참고해 여러분 서비스의 Tree를 그려주세요!",
    x: 75,
    y: 11020,
    width: 800,
    height: 300,
  },
];
